# Generated by Django 4.2.3 on 2023-08-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='default',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemail', models.CharField(max_length=64)),
                ('sender', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('time', models.CharField(max_length=64)),
            ],
        ),
    ]
