# Generated by Django 4.2.3 on 2023-09-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='receiver',
            field=models.CharField(default='2sd', max_length=64),
            preserve_default=False,
        ),
    ]
