# Generated by Django 4.2.3 on 2023-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='default',
            name='replied',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
