# Generated by Django 4.2.3 on 2023-08-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('REST', '0002_default_replied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default',
            name='replied',
        ),
    ]
